---
apiVersion: apps/v1
kind: Deployment                                # Type of the kubernetes resource
metadata:
  name: fullstack-postgres                       # Name of the deployment
  labels:                                        # Labels applied to this deployment
    app: fullstack-postgres
spec:
  selector:
    matchLabels:                                  # This deployment applies to the Pods matching the specified labels
      app: fullstack-postgres
      tier: postgres
  replicas: 1
  template:                                       # Template for the Pods in this deployment
    metadata:
      labels:                                     # Labels to be applied to the Pods in this deployment
        app: fullstack-postgres
        tier: postgres
    spec:                                         # The spec for the containers that will be run inside the Pods in this deployment
      containers:
        - image: postgres:latest                  # The container image
          name: postgres
          imagePullPolicy: "IfNotPresent"
          env:
            - name: POSTGRES_DB
              value: db1
            - name: POSTGRES_USER
              value: vtomar
            - name: POSTGRES_PASSWORD
              value: vtomar

          ports:
            - containerPort: 5432                   # The port that the container exposes
              name: postgres
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgres-persistent-storage     # This name should match the name specified in `volumes.name`
      volumes:
        - hostPath:
            path: "/home/docker/pgdata"
          name: postgres-persistent-storage


---
apiVersion: v1                                      # API version
kind: Service                                       # Type of kubernetes resource
metadata:
  name: fullstack-postgres                          # Name of the resource
  labels:                                           # Labels that will be applied to the resource
    app: fullstack-postgres
spec:
  type: NodePort
  ports:
    - nodePort: 32345
      port: 5432
  selector:                                         # Selects any Pod with labels `app=fullstack-postgres,tier=postgres`
    app: fullstack-postgres
    tier: postgres